#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('Mix Code Installer Demo Like Laravel Installer!', '1.0');

$app->add(new Acme\NewCommand(new GuzzleHttp\Client));

$app->run();